-- local expect = require("lib.expect")
-- local describe = require("lib.describe")
-- local it = require("lib.it")

-- describe:only("only describe", function()
-- 	it("only 1st", function()
-- 		expect(1 == 1).toBeTruthy()
-- 	end)
-- 	it("only 2nd", function()
-- 		expect(1 == 2).toBeFalsy()
-- 	end)
-- end)

-- describe("only it", function()
-- 	it("only 3rd", function()
-- 		expect(1 == 1).toBeTruthy()
-- 	end)
-- 	it:only("only 4th", function()
-- 		expect(1 == 2).toBeFalsy()
-- 	end)
-- end)

-- describe:only("both only it and describe", function()
-- 	it("only 5th", function()
-- 		expect(1 == 1).toBeTruthy()
-- 	end)
-- 	it:only("only 6th", function()
-- 		expect(1 == 2).toBeFalsy()
-- 	end)
-- end)
