local expect = require("lib.expect")
local describe = require("lib.classes.Describe")
local it = require("lib.classes.It")

describe:only("only describe", function()
	it("only 1st", function()
		expect(1 == 1).toBeTruthy()
	end)
	it("only 2nd", function()
		expect(1 == 2).toBeFalsy()
	end)
end)

describe("only it", function()
	it("only 3rd", function()
		expect(1 == 1).toBeTruthy()
	end)
	it:only("only 4th", function()
		expect(1 == 2).toBeFalsy()
	end)
end)

describe:only("both only it and describe", function()
	it("only 5th", function()
		expect(1 == 1).toBeTruthy()
	end)
	it:only("only 6th", function()
		expect(1 == 2).toBeFalsy()
	end)
end)

it:only("only standalone", function()
	expect(1 == 1).toBeTruthy()
end)

it("NOT only standalone", function()
	expect(1 == 1).toBeTruthy()
end)

describe("describe 2", function()
	it("describe 2 - 1", function()
		expect(1 == 1).toBeTruthy()
	end)

	describe("describe 3", function()
		it:only("describe 3 - 1", function()
			expect(1 == 1).toBeTruthy()
		end)
	end)
end)

describe:only("mixed only tests", function()
	-- it("hello", "world")
	it:skip("numbers should be equal", function()
		expect(1).toEqual(1)
	end)

	it("strings should be equal", function()
		expect("foo").toEqual("foo")
	end)

	it:skip("booleans should be equal", function()
		expect(true).toEqual(false)
	end)

	it:only("tables refs should be equal", function()
		local t1 = { a = 1 }
		expect(t1).toEqual(t1)
	end)

	it("nils should be equal", function()
		expect(nil).toEqual(nil)
	end)

	it("should be truly", function()
		expect(1 == 1).toBeTruthy()
	end)

	it("should be falsy", function()
		expect(1 == 2).toBeFalsy()
	end)

	it("should be nil", function()
		expect(nil).toBeNil()
	end)

	describe:only("level 1", function()
		it("to equal level 1", function()
			expect(1).toEqual(1)
		end)
		describe("Level 2", function()
			it("to equal level 2", function()
				expect(1).toEqual(1)
			end)
			it("to equal level 2", function()
				expect(1).toEqual(1)
			end)
			describe("Level 3", function()
				it("to equal level 3-1", function()
					expect(1).toEqual(1)
				end)
				it:skip("to equal level 3-2", function()
					expect(1).toEqual(1)
				end)
			end)
		end)
	end)
	it("to equal level 0-1", function()
		expect(1).toEqual(1)
	end)
	it("to equal level 0-2", function()
		expect(1).toEqual(1)
	end)
end)
