name: Tests
on: [push]
jobs:
  test:
    strategy:
      matrix:
        # TODO check merge for https://github.com/leafo/gh-actions-lua/pull/44
        # and use luajit-2.1
        luaVersion: ['5.1', '5.2', '5.3', '5.4', 'luajit-2.1.0-beta3']
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: test
        run: make test
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v9
      - uses: leafo/gh-actions-luarocks@v4

      - name: dependencies
        run: luarocks install luacheck

      - name: lint
        run: luacheck .
