name: Laura Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
      - uses: actions/checkout@master
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.4'
      - name: install
        run: make install
      - name: test
        run: make test
