name: Tests
on: [push]
jobs:
  test:
    strategy:
      matrix:
        # TODO check merge for https://github.com/leafo/gh-actions-lua/pull/44
        # and use luajit-2.1
        luaVersion: ['5.1', '5.2', '5.3', '5.4', 'luajit-openresty']
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - name: test
        run: make test
