name: Tests
on: [push]
jobs:
  test:
    strategy:
      matrix:
        # and use luajit-2.1
        luaVersion: ['5.1', '5.2', '5.3', '5.4', 'luajit-openresty']
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: test
        run: make test
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v11
      - uses: leafo/gh-actions-luarocks@v4

      - name: dependencies
        run: luarocks install luacheck

      - name: lint
        run: luacheck .
